### ISSUE TITLE
Is this package specific to Rozorpay or can we use this for any payment methods

### ISSUE THREAD

**Issue by MaheshPeri19** [gauravmehta13/razorpay_web#4]
Hi,

Is this package specific to Rozorpay or Can it accept for any payment gateway if we have API key and details ?

Please give suggestions on this.

**Comment by GauravCalidig** [comment]
This code is specific for Razorpay only, however  you can try other payment gateways by modifying the code  taking idea from here

**Comment by MaheshPeri19** [comment]
Okay. Thank you.
