### ISSUE TITLE
Not able to run in flutter web release mode, only working in local debug mode

### ISSUE THREAD

**Issue by muhd-ameen** [gauravmehta13/razorpay_web#7]
{
  "error": {
    "code": "BAD_REQUEST_ERROR",
    "description": "This business is not allowed to accept payments on this website. We suggest not going ahead with the payment.",
    "source": "internal",
    "step": "payment_initiation",
    "reason": "payment_risk_check_failed",
    "metadata": {
      "payment_id": "pay_Lig5g7vgSeTgtA"
    }
  }
}

This was the error returns while the payment was in release mode

**razorpay_web 1.3.6**  Im using this version 

Does anyone find the solution? @GauravCalidig @gauravmehta13

**Comment by gauravmehta13** [comment]
The issue seems to be with your razorpay account.
Please try another once and let me know if the issue persists.

**Comment by mhdaslam790** [comment]
i have got the same issue . did you got to know why it is not working?
